# Generated by Django 2.1.1 on 2018-10-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20181020_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='token_supply',
            new_name='supply',
        ),
    ]
