# Generated by Django 2.1.1 on 2018-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20181020_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='wallet_address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
